### PR TITLE
take clientId from gtag library

### PR DESCRIPTION
**Pull request by fstefan7**

### CODE REVIEW

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Comment by fstefan7** [comment]
[[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

**Review by edwardupton — CHANGES_REQUESTED** [review]

**Review by edwardupton — APPROVED** [review]

**Pull request merged**
